
services:
  ohms-backend:
    image: mufies14/ohms-backend:latest
    container_name: ohms-backend
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    environment:
      SPRING_DATASOURCE_URL: ${DATABASE_URL}
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      VIETQR_CLIENT_ID: ${VIETQR_CLIENT_ID}
      VIETQR_CLIENT_SECRET: ${VIETQR_CLIENT_SECRET}
      VIETQR_CHECKSUM_KEY: ${VIETQR_CHECKSUM_KEY}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
    networks:
      - ohms-network
    restart: unless-stopped

networks:
  ohms-network:
    driver: bridge