server:
  port: 8080
  tomcat:
    relaxed-query-chars: "|,{,},[,]"

spring:
  application:
    api-prefix: /api/v1
  security:
    oauth2:
      authorizedRedirectUris: http://localhost:5173/login/oauth2/code/google
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            scope:
              - openid
              - email
              - profile
  datasource:
    url: jdbc:mysql://localhost:3306/swpbackend?useSSL=false&serverTimezone=UTC
    username: root
    password: "root"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: haidang71214@gmail.com
    password: ojog ltyu idfa uyaw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  signal-key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"

gemini:
  api:
    key: AIzaSyB3NYOITWHAPBJMQ9vPyoT20WRoj8AObrE
    model: gemini-2.5-flash

payment:
  vn-pay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmn-code: CGCM5E2B
    secret-key: 45RSAWT0ILTS6QVETLWW4LRY9VCWVOQK
    return-url: http://localhost:5173/payment-callback
    version: 2.1.0
    command: pay
    order-type: other