server:
  port: 8080
  tomcat:
    relaxed-query-chars: "|,{,},[,]"

spring:
  application:
    api-prefix: /api/v1
  security:
    oauth2:
      authorizedRedirectUris: ${AUTHORIZED_REDIRECT_URIS:http://oachs-bucket.s3-website-ap-southeast-2.amazonaws.com/oauth2/redirect}
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI:http://3.107.211.186:8080/oauth2/callback/google}
            scope:
              - openid
              - email
              - profile
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://oachs.czyi4y4oucyu.ap-southeast-2.rds.amazonaws.com:3306/swpbackend?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${DATABASE_USERNAME:admin}
    password: ${DATABASE_PASSWORD:Maitri.104}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: haidang71214@gmail.com
    password: ojog ltyu idfa uyaw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  config:
    import: optional:file:.env[.properties]

app:
  signal-key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"

gemini:
  api:
    key: ${GEMINI_API_KEY}
    model: gemini-2.5-flash
vietqr:
  clientId: ${VIETQR_CLIENT_ID}
  clientSecret: ${VIETQR_CLIENT_SECRET}
  checksumKey: ${VIETQR_CHECKSUM_KEY}
payment:
  vn-pay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmn-code: CGCM5E2B
    secret-key: 45RSAWT0ILTS6QVETLWW4LRY9VCWVOQK
    return-url: http://localhost:5173/payment-callback
    version: 2.1.0
    command: pay
    order-type: other